package com.rapid.swifta;

public class TODOS {

    //TODO CREATE RATING API ✔
    //TODO FAVOURITES/LIKES ✔
    //TODO REQUEST TO ADD NEW SERVICE✔
    //TODO ENABLE REPORT USER✔
    //TODO CREATE YOUR DTOs
    //TODO FIX ALL THE REQUEST TYPES
    //TODO GLOBAL EXCEPTION HANDLING
    //TODO FIX ALL THE RETURN TYPES
    //TODO BOOK AHEAD/PRE-ORDER
    //TODO HIDE USER IF BUSY
    //TODO MAKE THE RANDOM SELECTION EXCLUDE THE OCCUPIED GUYS
    //TODO ENABLE THOSE FOR ONE OFF AND FOR CONTINUOUS
    //TODO NEW ROLE TO BE ADDED, MODERATOR
    //TODO ADD COMMENTS FOR EVERYTHING YOU'RE DOING
    //TODO COMMENT ON UserProps
    //TODO HIDE PASSWORD
    //TODO LOG IN AND SIGN UP
    //TODO CREATE ACTIVITY TABLE
    //TODO COUNT VERIFIED CLIENTS
    //TODO OUR ACHIEVEMENTS(LOCATIONS COUNT FOR COUNTRIES AND STATES)
    //TODO LEARN WEBSOCKETS AND ENABLE CHAT


}
