package com.rapid.swifta;

public class TODOS {

    //TODO CREATE RATING API ✔
    //TODO OUR ACHIEVEMENTS(LOCATIONS COUNT FOR COUNTRIES AND STATES)
    //TODO COUNT VERIFIED CLIENTS
    //TODO CREATE ACTIVITY TABLE
    //TODO LOG IN AND SIGN UP
    //TODO BOOK AHEAD/PRE-ORDER
    //TODO ENABLE THOSE FOR ONE OFF AND FOR CONTINUOUS
    //TODO NEARBY FILLING STATIONS AND THEIR PRICES AND LOCATIONS
    //TODO COMMENT ON UserProps
    //TODO RATING BASED ON SPEED OF DELIVERY


}
