package com.rapid.swifta;

public class TODOS {

    //TODO CREATE RATING API           ✔
    //TODO FAVOURITES/LIKES            ✔
    //TODO REQUEST TO ADD NEW SERVICE  ✔
    //TODO ENABLE REPORT USER          ✔
    //TODO CREATE YOUR DTOs            ✔
    //TODO FIX ALL THE REQUEST AND RETURN TYPES        ✔
    //TODO TEST ALL ENDPOINTS                          ✔
    //TODO ENSURE THAT YOU TIE THE ORDER_DETAILS AND ORDERS PROPERLY ✔
    //TODO FIX ALL THE RETURN TYPES ✔
    //TODO PUT DESCRIPTION FOR BULK SEARCH
    //TODO IN THE USER RESPONSE DTO FOR PAGEABLE RESPONSES, IDENTIFY WHO'S A FAVOURITE AND WHO ISN'T      ✔
    //TODO ADD JOB DESCRIPTION AND AMOUNT(WORTH) TO USER RESPONSE DTO                                     ✔


    //TODO LOCATE ALL SIGNED IN USER
    //TODO SERVICES RATING                        ✔
    //TODO HANDLE ATTACHMENTS (SERVICES, USERS)

    //TODO ENABLE REQUEST OF MULTIPLE MERCHANTS
    //TODO GLOBAL EXCEPTION HANDLING
    //TODO ENABLE BROADCASTS
    //TODO ENABLE SEARCH FOR UNSIGNED IN USERS

    //TODO ADD TITLE SEARCH
    //TODO ADD SKILLS
    //TODO CREATE AN ENTIRE SERVICE CLASS JUST LIKE THE USER
    //TODO RESTRICT ALL USER SEARCH/RANDOM TO ONLY USERS
    //TODO ONCE THE BROADCAST IS ACCEPTED, DISABLE OTHERS WHO GOT IT FROM ENGAGING
    //TODO BOOK AHEAD/PRE-ORDER
    //TODO ENABLE REQUEST TO HAVE A SECOND ROLE AFTER HAVING ONE
    //TODO HIDE USER IF BUSY
    //TODO MAKE THE RANDOM SELECTION EXCLUDE THE OCCUPIED GUYS
    //TODO ENABLE THOSE FOR ONE OFF AND FOR CONTINUOUS
    //TODO NEW ROLE TO BE ADDED, MODERATOR
    //TODO ADD COMMENTS FOR EVERYTHING YOU'RE DOING
    //TODO SEPARATE CONCERNS BY CLASS DEPENDING ON AUTHORIZATION
    //TODO COMMENT ON UserProps
    //TODO IDENTIFY ALL THE PLACES WHERE SIGNED IN USER IS REQUIRED
    //TODO HIDE PASSWORD
    //TODO LOG IN AND SIGN UP
    //TODO MERCHANT TO SET STATUS TO IS_BUSY ONCE HE ACCEPTS AN ORDER
    //TODO ENABLE JOB BROADCAST ALONG WITH TIME OF DELIVERY
    //TODO ENABLE BROADCAST FOR ONLY THOSE WHO HAVE MONEY IN THE WALLET WHICH YOU'RE GOING TO CREATE
    //TODO ENABLE BROADCASTS BASED ON JOBS PAID FOR AND THROUGH OUR PLATFORMS
    //TODO DISABLE BROADCAST AFTER TWO TRIES, SEND WARNING

    //TODO ENSURE YOU GO THROUGH EVERY CREATED BY AND UPDATE IT FROM THE CURRENT SETTINGS
    //TODO CREATE ACTIVITY TABLE
    //TODO COUNT VERIFIED CLIENTS
    //TODO OUR ACHIEVEMENTS(LOCATIONS COUNT FOR COUNTRIES AND STATES)
    //TODO LEARN WEBSOCKETS AND ENABLE CHAT
    //TODO AVERAGE RESPONSE TIME(TIME IT TAKES FOR USER TO RESPOND TO TEXT)


//    Description, Rating, jobCount


    //
}
